import arraySortPositions from '../../legacy/libs/arraySortPositions.mjs';
import asyncReplace from '../../legacy/libs/replaceAsync.mjs';
import { shuffleArray } from './array.mjs';
import { formatCustomTimer, formatDayTimer, formatTimer, getTimeDuration } from './clock.mjs';
import {
  readJsonBlob,
  saveJsonFile,
  fetchJson,
  installWindowHiddenScript,
  readFileBlob,
  readBase64Blob,
  fetchText,
} from './html.mjs';
import {
  areHtmlElsColliding,
  getHtmlElBorders,
  getHtmlElBordersWidth,
  getHtmlElMargin,
  getHtmlElPadding,
  isInViewport,
  isScrolledIntoView,
} from './html_deprecated.mjs';
import { extendObjType, reorderObjTypeOrder, cloneObjTypeOrder, objType } from './objFilter.mjs';
import { countObj, isJsonObject } from './objChecker.mjs';
import {
  documentIsFullScreen,
  isScreenFilled,
  requestFullScreen,
  exitFullScreen,
  isFullScreenMode,
  onFullScreenChange,
  offFullScreenChange,
} from './fullScreen.mjs';
import {
  formatBytes,
  genFibonacciSeq,
  getAge,
  getPercentage,
  getSimplePerc,
  ruleOfThree,
} from './simpleMath.mjs';
import { addAiMarkerShortcut, safeTextTrim, toTitleCase, toTitleCaseLowerFirst } from './text.mjs';
import {
  areElsCollTop,
  areElsCollBottom,
  areElsCollLeft,
  areElsCollRight,
  areElsCollPerfTop,
  areElsCollPerfBottom,
  areElsCollPerfLeft,
  areElsCollPerfRight,
  areElsColliding,
  areElsPerfColliding,
  getElsColliding,
  getElsPerfColliding,
  getElsCollOverlap,
  getElsCollOverlapPos,
  getRectCenter,
  getElsRelativeCenterOffset,
  getElsCollDirDepth,
  getElsCollDetails,
} from './collision.mjs';

export {
  getPercentage,
  areElsCollTop,
  areElsCollBottom,
  areElsCollLeft,
  areElsCollRight,
  areElsCollPerfTop,
  areElsCollPerfBottom,
  areElsCollPerfLeft,
  areElsCollPerfRight,
  areElsColliding,
  areElsPerfColliding,
  getElsColliding,
  getElsPerfColliding,
  getElsCollOverlap,
  getElsCollOverlapPos,
  getRectCenter,
  getElsRelativeCenterOffset,
  getElsCollDirDepth,
  getElsCollDetails,
  isInViewport,
  isScrolledIntoView,
  safeTextTrim,
  installWindowHiddenScript,
  genFibonacciSeq,
  getHtmlElBorders,
  getHtmlElBordersWidth,
  getHtmlElMargin,
  getHtmlElPadding,
  fetchJson,
  fetchText,
  readJsonBlob,
  readFileBlob,
  readBase64Blob,
  saveJsonFile,
  documentIsFullScreen,
  isScreenFilled,
  requestFullScreen,
  exitFullScreen,
  isFullScreenMode,
  onFullScreenChange,
  offFullScreenChange,
  areHtmlElsColliding,
  isJsonObject,
  arraySortPositions,
  formatBytes,
  addAiMarkerShortcut,
  extendObjType,
  reorderObjTypeOrder,
  cloneObjTypeOrder,
  countObj,
  objType,
  ruleOfThree,
  getSimplePerc,
  asyncReplace,
  getAge,
  formatCustomTimer,
  formatDayTimer,
  formatTimer,
  getTimeDuration,
  shuffleArray,
  toTitleCase,
  toTitleCaseLowerFirst,
};
